## Settings
title: Blog
owner: "95ych"
url: "https://95ych.github.io"
baseurl: "/academic-journal"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "cyksagar@protonmail.com"
github: "95ych"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by DeerRIDER"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
